spring:
  datasource:
    username: root
    password: kangta27
    url:  jdbc:mysql://localhost:3306/testjava?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8989

logging:
  level:
    org.springframework.orm.jpa: debug

