server:
  port: 8087
spring:
  datasource:
    username: root
    password: kangta27
    url:  jdbc:mysql://localhost:3306/springbootdb?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 50
        max-wait: 3000ms
        max-idle: 20
        min-idle: 10
    timeout: 5000ms

mybatis:
  type-aliases-package: com.dwt.springbootmybatis.domain
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
logging:
  level:
    com:
      dwt:
        springbootmybatis:
          mapper: debug

