spring:
  application:
    name: HelloWorldZKProvider
  cloud:
    zookeeper:
      discovery:
        enabled: true
      connect-string: localhost:2181

server:
  port: 8099
endpoints:
  restart:
    enabled: true
logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN


