server:
  port: 9002
spring:
  application:
    name: Consumer
  cloud:
    zookeeper:
      discovery:
        enabled: true
#        root: /testconsumer
      connect-string: localhost:2181
logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN
    com.dwt.springbootzookeeperconsumer: INFO
