server:
  port: 8989
  servlet:
    context-path: /demo
spring:
  kafka:
    producer:
      properties:
        spring:
          json:
            trusted:
              packages: "com.learning.kafka.domain"
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "com.learning.kafka.domain"
